[package]
name = "json-ld"
version = "0.4.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"
categories = ["web-programming", "database", "data-structures"]
keywords = ["json-ld", "json", "semantic-web", "linked-data", "rdf"]
description = "A JSON-LD implementation"
repository = "https://github.com/timothee-haudebourg/json-ld"
documentation = "https://docs.rs/json-ld"
license = "MIT/Apache-2.0"
readme = "README.md"

exclude = [
	"/json-ld-api"
]

[features]
reqwest-loader = ["reqwest"]
test = ["generic-json/ijson-impl"]

[dependencies]
log = "^0.4"
derivative = "*"
mown = "^0.2"
# cc-traits = "^0.6"
cc-traits = { path = "../../traits/cc-traits" }
# generic-json = "^0.1"
generic-json = { path = "../../json/generic", features = ["nightly"] }
iref = "^2.0.3"
futures = "^0.3"
once_cell = "^1.4"
reqwest = { version = "^0.11", optional = true }
langtag = "^0.2"

[dev-dependencies]
async-std = { version = "^1.5", features = ["attributes"] }
static-iref = "^1.0"
iref-enum = "^1.2"
stderrlog = "^0.5"
tokio = { version = "^1.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
ijson = "^0.1"

[[example]]
name = "compaction"
required-features = ["generic-json/ijson-impl"]

[[example]]
name = "expansion"
required-features = ["generic-json/ijson-impl"]

[[example]]
name = "custom-ids"
required-features = ["generic-json/ijson-impl"]

[[example]]
name = "custom-ids-iref-enum"
required-features = ["generic-json/ijson-impl"]

[[example]]
name = "generate-compact-tests"
required-features = ["generic-json/ijson-impl"]

[[example]]
name = "generate-expand-tests"
required-features = ["generic-json/ijson-impl"]

[[example]]
name = "reqwest-loader"
required-features = ["generic-json/ijson-impl", "reqwest-loader"]