[package]
name = "json-ld"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@ens-rennes.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
mown = "0.2.0"
json = "*"
iref = "1.1.3"
reqwest = { version = "0.10" }
futures = "0.3"
static-iref = "*"

[dev-dependencies]
tokio = "*"
stderrlog = "*"
