[package]
name = "json-ld"
version = "0.0.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"

[features]
reqwest-loader = ["reqwest"]

[dependencies]
log = "*"
mown = "0.2.0"
json = "*"
iref = "1.1.5"
futures = "0.3"
reqwest = { version = "0.10", optional = true }

[dev-dependencies]
static-iref = "*"
stderrlog = "*"
tokio = "*"

[[example]]
name = "generate-expand-tests"
required-features = ["reqwest-loader"]
