[package]
name = "json-ld"
version = "0.0.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"

[dependencies]
log = "*"
mown = "0.2.0"
json = "*"
iref = "1.1.3"
reqwest = { version = "0.10" }
futures = "0.3"
static-iref = "*"

[dev-dependencies]
tokio = "*"
stderrlog = "*"
