[package]
name = "json-ld-testing"
version = "0.1.0"
edition = "2021"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
description = "Testing library for the `json-ld` library"
categories = ["web-programming", "database", "data-structures"]
keywords = ["json-ld", "json", "semantic-web", "linked-data", "rdf"]
repository = "https://github.com/timothee-haudebourg/json-ld"
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
json-ld = { path = "../json-ld" }
syn = { version = "1.0", features = ["full"] }
litrs = "0.2.3"
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"