[package]
name = "json-ld-core"
version = "0.6.1"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2021"
categories = ["web-programming", "database", "data-structures"]
keywords = ["json-ld", "json", "semantic-web", "linked-data", "rdf"]
description = "A JSON-LD implementation"
repository = "https://github.com/timothee-haudebourg/json-ld"
documentation = "https://docs.rs/json-ld"
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
reqwest-loader = ["reqwest"]
uuid-generator-v3 = ["uuid", "uuid/v3"]
uuid-generator-v4 = ["uuid", "uuid/v4"]
uuid-generator-v5 = ["uuid", "uuid/v5"]
default = ["uuid-generator-v3", "uuid-generator-v4", "uuid-generator-v5"]

[dependencies]
json-ld-syntax = { path = "../syntax" }
json-syntax = "0.4"
json-number = "0.3"
log = "^0.4"
derivative = "^2.2"
mown = "^0.2"
iref = "^2.1"
static-iref = "1.0"
futures = "^0.3"
once_cell = "^1.4"
reqwest = { version = "^0.11", optional = true }
langtag = "^0.2"
uuid = { version = "0.8", optional = true }
smallvec = "*"
permutohedron = { version = "0.2" }
pretty_dtoa = "0.3"
rdf-types = "0.7"
locspan = "0.7.2"
locspan-derive = "0.5.1"


[dev-dependencies]
async-std = { version = "^1.5", features = ["attributes"] }
static-iref = "^1.0"
iref-enum = "^1.2"
stderrlog = "^0.5"
tokio = { version = "^1.0", features = ["macros", "rt-multi-thread"] }
itertools = "0.10"
grdf = "0.4.2"
nquads-syntax = "0.1.6"